apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.datacollectorservice.application }}-admin
  namespace: {{ .Values.datacollectorservice.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "001"
    "helm.sh/hook-delete-policy": before-hook-creation
