datacollectorservice:
  application: data-collector-service
  image:
    registry: registry.hub.docker.com/library
    name: busybox
    version: 1.35.0
    
  port:
    name: data-collector-port
    number: 2500
  replicaCount: 2
  repository: busybox
  service:
    name: data-collector-svc
    port: 8080
    type: ClusterIP
  
  serviceAccountName: data-collector-admin
  stage: development
  tier: backend
  version: 0.0.1
