datacollectorservice:
  application: data-collector
  name: data-collector-service
  namespace: data-collector-service
  image:
    registry: registry.hub.docker.com/library
    name: busybox
    version: 1.36.0
    
  port:
    name: datac-port
    number: 2500
  replicaCount: 2
  service:
    name: data-collector-svc
    port: 8080
    type: ClusterIP
  
  stage: development
  tier: backend
  version: 0.0.1
